# Generated by Django 5.2.2 on 2025-06-05 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_passwordresetotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealplan',
            name='recipes',
            field=models.ManyToManyField(blank=True, through='api.Have', to='api.recipe'),
        ),
    ]
